# -*- coding: utf-8 -*-
# 像素怪物贴图设计 (16 行 x 16 列, '.' 为透明)
# 色板键: K # D 0 L 7 W S $ & 8 9 R r A x X w 4 O % 2 Y F ! 5
#         G i g j V h 3 C c k ~ T I 1 B b u U P p Q v @ M m ;
#         N n H J 6 E e Z
DESIGNS = {
    # 狼: 灰蓝皮毛(0/L/7/S), 尖耳竖立, 白色腹部, 红眼, 咧嘴露齿, 四肢着地
    "wolf": [
        "....KK..KK......",
        "...KSSK..KSSK...",
        "...KSSSSSSSK....",
        "..KSSSSSSSSSK...",
        "..KSSXSSSSXSSK..",
        ".KSSSSSNSSSSSSK.",
        ".KSSSRRRRRRSSSK.",
        "KSSSSSSSSSSSSSSK",
        "KSSSWWWWWWWWSSSK",
        "KSSSSSSSSSSSSSSK",
        "..KSSK....KSSK..",
        "..KSSK....KSSK..",
        "..KSSK....KSSK..",
        "..KSSK....KSSK..",
        "..KSSK....KSSK..",
        "..KSSK....KSSK..",
    ],

    # 食人魔: 暗绿巨肌(G/g/h/V), 庞大身躯, 棕色兽皮披肩(n/J), 獠牙(8), 小眼, 手持木棒(N)
    "ogre": [
        "..KKKKKKKKKKKK..",
        ".KJJGGGGGGGGJJK.",
        ".KGgGGGGGGGGgGK.",
        ".KXGgGGGGGGgGXK.",
        ".KGgGGGGGGGGgGK.",
        ".KGGN8GGGG8NGGK.",
        ".KGgGGGGGGGGgGK.",
        ".KGGGGGGGGGGGGK.",
        ".KJJGGGGGGGGJJK.",
        ".KGGGGGGGGGGGGK.",
        ".KGGGGGGGGGGGGK.",
        "KGGGGGGGGGGGGGGK",
        "KGgGGGGGGGGGGgGK",
        "KGGGGGGGGGGGGGGK",
        ".KGGGGGGGGGGGGK.",
        "..KKKKKKKKKKKK..",
    ],

    # 石魔像: 岩石灰蓝(0/L/D/7), 方块感强, 头上有花草(绿), 眼睛发光(B/u青)
    "golem": [
        "..jjKKKKKKKKjj..",
        "...KDDDDDDDDK...",
        "...KD0DDDD0DK...",
        "...KBuDDDDuBK...",
        "..KDDDDDDDDDDK..",
        "..KD0D0D0D0DDK..",
        ".KDDDDDDDDDDDDK.",
        ".KD0DDDDDDDD0DK.",
        ".KDDDDDDDDDDDDK.",
        ".KD0D0D0D0D0DDK.",
        ".KDDDDDDDDDDDDK.",
        "KDDDDDDDDDDDDDDK",
        "KDD0DDDDDDDD0DDK",
        "KDDDDDDDDDDDDDDK",
        ".KDDDDDDDDDDDDK.",
        "..KKKKKKKKKKKK..",
    ],

    # 堕落骑士: 暗金属铠甲(0/&/S/D), 头盔带缝, 眼睛透红光(R/x), 十字纹章
    "knight": [
        "....KKKKKKKK....",
        "...KDDDDDDDDK...",
        "...KD0DDDD0DK...",
        "..KDS0DDDD0SDK..",
        "..KDRR0KK0RRDK..",
        ".KD0D0DDDD0D0DK.",
        ".KDDDDDDDDDDDDK.",
        ".KS0SSSSSSSS0SK.",
        ".KSSS0SKS0SSSSK.",
        ".KSSSSSSSSSSSSK.",
        ".KSSSSSSSSSSSSK.",
        "KSSS0SSSSSS0SSSK",
        "KS0SSSSSSSSSS0SK",
        "KSSSSSSSSSSSSSSK",
        ".KSSSSSSSSSSSSK.",
        "..KKKKKKKKKKKK..",
    ],

    # 龙: 红色巨龙(R/X/A/4), 张翼, 头上有角(8), 金色肚皮(F/!/5), 尖牙
    "dragon": [
        "..KK......KK....",
        ".KRRK....KRRK...",
        ".KR88RRRRRR88RK.",
        ".KRRRRRRRRRRRRK.",
        "KRRRRXXRRXXRRRRK",
        "KRRRR88RR88RRRRK",
        "KRRRRRRRRRRRRRRK",
        ".KRRRRRRRRRRRRK.",
        "KRRRRFFFFRRRRRRK",
        "KRrFFFFFFFFFFrRK",
        "KRrFFFFFFFFFFrRK",
        "KRrFFFFFFFFFFrRK",
        ".KRRrFFFFFFrRRK.",
        ".KRRRrRRRRrRRRK.",
        ".KRRRRRrRRRRRRK.",
        "..KKKKKKKKKKKK..",
    ],

    # 巫妖: 紫色法袍(P/p/Q), 骷髅头(8), 眼中幽光(C/k), 头戴冠
    "lich": [
        "....888888......",
        "...8N88N88N8....",
        "..88888888888...",
        "..8k88888888k8..",
        "..888888888888..",
        "...888888888....",
        "...88888N888....",
        "..PPPPPPPPPP....",
        "..PPpPPPPpPP....",
        "..PPPPPPPPPP....",
        "..PpPPPPPPpP....",
        "..PPPPPPPPPP....",
        "..PPPPPPPPPP....",
        "..PPP..PPP......",
        "..PPP..PPP......",
        "..PP....PP......",
    ],

    # 幽灵: 半透明白色(1/I/7/白), 下部飘散渐隐, 青色眼睛(C/k)
    "ghost": [
        ".......11.......",
        "......1111......",
        ".....111111.....",
        ".....1C11C1.....",
        "....11111111....",
        "....11771177....",
        "...1111111111...",
        "...1177117711...",
        "...1111111111...",
        "..111111111111..",
        "..117111111171..",
        "..111111111111..",
        "..177111111771..",
        "..177177117717..",
        "...1777711777...",
        "....1777..777...",
    ],

    # 女妖: 苍白色脸(8/7/E), 长黑发(#/D), 尖叫血盆大口(R/r), 绿光眼眶
    "banshee": [
        "..############..",
        ".##############.",
        ".##8888888888##.",
        ".##8k888888k8##.",
        ".##8888888888##.",
        ".##88RRRRRR88##.",
        ".##88RRRRRR88##.",
        ".##88R888R888##.",
        ".##8888888888##.",
        ".##8888888888##.",
        ".##8EEEEEEEE8##.",
        ".##############.",
        "..############..",
        "..############..",
        "...##########...",
        "....########....",
    ],

    # 怨魂: 黑紫色影(@/Q/p), 红色燃烧眼(R/x), 缠身绿色怨气(j/g), 飘浮袍状
    "wraith": [
        ".......@@.......",
        "......@QQ@......",
        ".....@QQQQ@.....",
        ".....@RQQRQ@....",
        "....@QQQQQQ@....",
        "....@QQQQQQQ@...",
        "...@QQQQQQQQ@...",
        "...@QQQQQQQQ@...",
        "..@QQQQQQQQQQ@..",
        "..@QQpQQQQpQQ@..",
        "..@QQQQQQQQQQ@..",
        "..@QQpQQQQpQQ@..",
        ".@QQQQQQQQQQQQ@.",
        ".@gQQQQQQQQQQg@.",
        "..gjQQQQQQQQjg..",
        "...jQQQQQQQQj...",
    ],

    # 死亡蜘蛛: 黑色/紫色身体(K/@/P), 8条腿, 红色眼睛, 腹部斑纹(R/p)
    "deathspider": [
        "K.K........K.K..",
        ".K.K......K.K...",
        "..K.K....K.K....",
        "...K.K..K.K.....",
        "....KK..KK......",
        "....KXR@RXK.....",
        "...K@@@@@@K.....",
        "..K@@@@@@@@K....",
        "...K@@RR@@K.....",
        "....KKRRKK......",
        "....KK..KK......",
        "...K.K..K.K.....",
        "..K.K....K.K....",
        ".K.K......K.K...",
        "K.K........K.K..",
        "K.............K.",
    ],
}
